#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require "patch_util"

begin
  PatchUtil::CLI.start(ARGV)
rescue PatchUtil::Error => e
  warn e.message
  exit 1
end
